-- Step 1: Create dispute_reasons table
CREATE TABLE dispute_reasons (
  dispute_reason_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR NOT NULL UNIQUE
);

-- Step 2: Insert unique reasons from disputes
INSERT INTO dispute_reasons (description)
SELECT DISTINCT reason FROM disputes;

-- Step 3: Add dispute_reason_id and details columns to disputes
ALTER TABLE disputes
ADD COLUMN dispute_reason_id INT,
ADD COLUMN details VARCHAR;

-- Step 4: Update disputes with the corresponding dispute_reason_id and details
UPDATE disputes d
SET dispute_reason_id = dr.dispute_reason_id,
    details = d.reason
FROM dispute_reasons dr
WHERE d.reason = dr.description;

-- Step 5: Add foreign key constraint
ALTER TABLE disputes
ADD CONSTRAINT fk_dispute_reason
FOREIGN KEY (dispute_reason_id)
REFERENCES dispute_reasons(dispute_reason_id);
