CREATE TABLE allowed_dispute_progressions (
  allowed_dispute_progression_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_dispute_id int NOT NULL REFERENCES dispute_statuses (dispute_status_id),
  to_dispute_id int NOT NULL REFERENCES dispute_statuses (dispute_status_id)
);

INSERT INTO allowed_dispute_progressions (from_dispute_id, to_dispute_id)
VALUES (1, 2), (2, 3), (2, 4);