@startuml
title GET /dispute-statuses - List Dispute Statuses

participant "Client" as C
participant "ReferenceDataController" as RDC
participant "IReferenceDataService" as RDS
participant "IDisputeStatusRepository" as DSR
participant "[DB]" as DB

C -> RDC: GET /dispute-statuses
activate RDC
RDC -> RDS: ListDisputeStatuses()
activate RDS
RDS -> DSR: FindAllDisputeStatuses()
activate DSR
DSR -> DB: Execute SELECT query for all dispute_statuses
activate DB
DB --> DSR: DisputeStatus Records
deactivate DB
DSR -> DSR: Map Records to List<DisputeStatusModel>
DSR --> RDS: List<DisputeStatusModel>
deactivate DSR
RDS -> RDS: Map Models to List<DisputeStatusDto>
RDS --> RDC: List<DisputeStatusDto>
deactivate RDS
RDC -> C: 200 OK \nContent: List<DisputeStatusDto>
deactivate RDC

alt Error
    RDC -> C: 500 Internal Server Error
end
@enduml