name: Deploy DB Migrations
description: Deploy DB Migrations to the database using Flyway

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Galaxy Bank Main Deploy V1"]
    branches: [main]
    types: [completed]

env:
  AWS_REGION: af-south-1

jobs:
  migrate:
    name: Run DB migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assume the deployment user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialise Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform output
        run: |
          cd terraform
          terraform init
          terraform output

      - name: Get Terraform Outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs
        with:
          path: terraform

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run Flyway validate and migrate
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://${{ steps.tf-outputs.outputs.rds_endpoint }}/galaxy_db
          user: galaxy
          password: password
          locations: filesystem:flyway/sql/migrations