name: Galaxy Bank Main Deploy V1
description: Deploys the Galaxy Bank application to AWS ECS using Terraform and Docker.

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  WORKING_DIRECTORY: ./Api
  AWS_REGION: af-south-1

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Assume the deployment user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Extract Terraform Outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs
        with:
          path: terraform

      - name: Publish image to ECR
        run: |
          REPOSITORY_URI=${{ steps.tf-outputs.outputs.ecr_repository_url }}
          IMAGE_TAG=latest

          cd Api
          docker build -t $REPOSITORY_URI:$IMAGE_TAG .
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
          docker push $REPOSITORY_URI:$IMAGE_TAG

      - name: Perform ECS deployment
        run: |
          CLUSTER_NAME="${{ steps.tf-outputs.outputs.ecs_cluster_name }}"
          SERVICE_NAME="${{ steps.tf-outputs.outputs.ecs_service_name }}"
          aws ecs update-service --cluster "$CLUSTER_NAME" --service "$SERVICE_NAME" --force-new-deployment
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
