name: Deploy DB Migrations
description: Deploy DB Migrations to the database using Flyway

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  migrate:
    name: Run DB migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run Flyway validate and migrate
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://${{ secrets.RDS_HOSTNAME }}:5432/galaxy_db
          user: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          locations: filesystem:flyway/sql/migrations